### ISSUE TITLE
Jenkins on the server cannot download plugins

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [rework-space-com/bigtop#14]
## Description
After running jenkins in the docker container on the server, plugins cannot be downloaded:

![Image](https://github.com/TNTU-RS-internship/bigtop/assets/72742712/cc21ab07-0ba5-4677-ba3c-a0824f518d53)

**Comment by Nazarii-Melnyk** [comment]
That what jenkins writes in the logs:
```
2024-02-14 11:51:07.923+0000 [id=95]	SEVERE	h.model.UpdateCenter$DownloadJob#run: Failed to install structs
java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:589)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2922)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2831)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1927)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1321)
Caused: java.io.IOException: Failed to load https://updates.jenkins.io/download/plugins/structs/337.v1b_04ea_4df7c8/structs.hpi to /var/jenkins_home/plugins/structs.jpi.tmp
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1332)
Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/structs/337.v1b_04ea_4df7c8/structs.hpi (redirected to: https://get.jenkins.io/plugins/structs/337.v1b_04ea_4df7c8/structs.hpi)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1366)
	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1923)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2235)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1897)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:121)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by Nazarii-Melnyk** [comment]
@RomanButsiy Hi ✋ 
I started container with jenkins on the server, but jenkins can't download any plugins. Do you have any idea what the problem is?

**Comment by RomanButsiy** [comment]
@Nazarii-Melnyk Hi ✋
Your problem to be related to discrepancies in the MTU (Maximum Transmission Unit) values between the network interface of the virtual machine and Docker. MTU defines the maximum size of data packets that can be transmitted over a network. If the Docker container's MTU is higher than the MTU of the network it tries to connect to, it can lead to network issues, such as being unable to download plugins for Jenkins.
To solve this issue, you need to specify Docker to use the same MTU value as your virtual machine's network interface. Follow these steps:
1. Open the `/etc/docker/daemon.json` file in a text editor on the server where Docker is running. If the file does not exist, create it.
2. Add or modify the following configuration parameter:
```json
{
    "mtu": 1450
}
```
This configuration file instructs Docker to use an MTU size of 1450, matching the MTU of your virtual machine.
3. After making the changes, save the file and close the editor.
4. Restart the Docker service to apply the changes. This can be done with the following command in the terminal:
```bash
sudo systemctl restart docker
```
After restarting the Docker service, try to run the Jenkins container again and check if the problem with downloading plugins has been resolved

**Comment by Nazarii-Melnyk** [comment]
@RomanButsiy 
Understood, thank you! 👍

**Comment by Nazarii-Melnyk** [comment]
Problem was resolved and Jenkins downloaded needful plugins👌
