### ISSUE TITLE
Fix HDFS YARN and Ambari Metrics dashboards

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [rework-space-com/bigtop#28]
# Description
Ambari Metrics returns "No Data Available" on many dashboards of HDFS, YARN and Ambari Metrics also:

![image](https://github.com/user-attachments/assets/d71043fa-e897-413b-a5c3-3afe554abc51)

![image](https://github.com/user-attachments/assets/10618979-28c1-427f-a1f2-717e3e673039)

![image](https://github.com/user-attachments/assets/9910b810-2cb5-4411-af94-2492f6a07fdf)

**Comment by Nazarii-Melnyk** [comment]
```
INFO [main] AmbariMetricSinkImpl:182 - Exception caught when retrieving Collector URI
org.apache.ambari.server.ServiceNotFoundException: Service not found, clusterName=bigtop, serviceName=AMBARI_METRICS
        at org.apache.ambari.server.state.cluster.ClusterImpl.getService(ClusterImpl.java:895)
        at org.apache.ambari.server.metrics.system.impl.AmbariMetricSinkImpl.init(AmbariMetricSinkImpl.java:147)
        at org.apache.ambari.server.metrics.system.impl.MetricsServiceImpl.initializeMetricsSink(MetricsServiceImpl.java:85)
        at org.apache.ambari.server.metrics.system.impl.MetricsServiceImpl.start(MetricsServiceImpl.java:58)
        at org.apache.ambari.server.controller.AmbariServer.run(AmbariServer.java:598)
        at org.apache.ambari.server.controller.AmbariServer.main(AmbariServer.java:1113)
```

**Comment by Nazarii-Melnyk** [comment]
Ambari Server logs:
```
ERROR [ambari-client-thread-11304] MetricsRequestHelper:112 - Error getting timeline metrics : Connection refused (Connection refused)
2024-08-14 12:17:50,938 ERROR [ambari-client-thread-11304] MetricsRequestHelper:119 - Cannot connect to collector: SocketTimeoutException for isv-s-hdp-mng-01.example.com
```

**Comment by Nazarii-Melnyk** [comment]
Ambari Server logs:
```
WARN [ambari-client-thread-13910] UpdatingSelfPopulatingCache:117 - timelineMetricCacheCould not refresh element TimelineAppMetricCacheKey{metricNames=[cpu_wio, cpu_user, mem_free, cpu_nice, cpu_idle, cpu_system, mem_total], appId='isv-s-hdp-mst-01.example.com', hostNames=NAMENODE, spec='http://isv-s-hdp-mng-01.example.com:6188/ws/v1/timeline/metrics?metricNames=cpu_wio%2Ccpu_user%2Cmem_free%2Ccpu_nice%2Ccpu_idle%2Ccpu_system%2Cmem_total&hostname=isv-s-hdp-mst-01.example.com&appId=HOST&startTime=1723634214&endTime=1723637814'}
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:465)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:560)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:244)
        at sun.net.www.http.HttpClient.New(HttpClient.java:341)
        at sun.net.www.http.HttpClient.New(HttpClient.java:359)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1228)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1572)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at org.apache.ambari.server.controller.internal.URLStreamProvider.processURL(URLStreamProvider.java:237)
        at org.apache.ambari.server.controller.internal.URLStreamProvider.processURL(URLStreamProvider.java:155)
        at org.apache.ambari.server.controller.metrics.timeline.MetricsRequestHelper.fetchTimelineMetrics(MetricsRequestHelper.java:79)
        at org.apache.ambari.server.controller.metrics.timeline.cache.TimelineMetricCacheEntryFactory.updateEntryValue(TimelineMetricCacheEntryFactory.java:172)
        at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.refreshElement(SelfPopulatingCache.java:267)
        at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.refreshElement(SelfPopulatingCache.java:242)
        at net.sf.ehcache.constructs.blocking.UpdatingSelfPopulatingCache.update(UpdatingSelfPopulatingCache.java:112)
        at net.sf.ehcache.constructs.blocking.UpdatingSelfPopulatingCache.get(UpdatingSelfPopulatingCache.java:83)
        at org.apache.ambari.server.controller.metrics.timeline.cache.TimelineMetricCache.get(TimelineMetricCache.java:137)
        at org.apache.ambari.server.controller.metrics.timeline.cache.TimelineMetricCache.getAppTimelineMetricsFromCache(TimelineMetricCache.java:68)
        at org.apache.ambari.server.controller.metrics.timeline.AMSPropertyProvider$MetricsRequest.getTimelineMetricsFromCache(AMSPropertyProvider.java:199)
        at org.apache.ambari.server.controller.metrics.timeline.AMSPropertyProvider$MetricsRequest.populateResources(AMSPropertyProvider.java:247)
        at org.apache.ambari.server.controller.metrics.timeline.AMSPropertyProvider.populateResourcesWithProperties(AMSPropertyProvider.java:544)
at org.apache.ambari.server.controller.metrics.MetricsPropertyProvider.populateResources(MetricsPropertyProvider.java:154)
        at org.apache.ambari.server.controller.metrics.MetricsPropertyProviderProxy.populateResources(MetricsPropertyProviderProxy.java:197)
        at org.apache.ambari.server.controller.internal.StackDefinedPropertyProvider.populateResources(StackDefinedPropertyProvider.java:220)
        at org.apache.ambari.server.controller.internal.ClusterControllerImpl.populateResources(ClusterControllerImpl.java:153)
        at org.apache.ambari.server.api.query.QueryImpl.queryForResources(QueryImpl.java:424)
        at org.apache.ambari.server.api.query.QueryImpl.execute(QueryImpl.java:222)
        at org.apache.ambari.server.api.handlers.ReadHandler.handleRequest(ReadHandler.java:77)
        at org.apache.ambari.server.api.services.BaseRequest.process(BaseRequest.java:144)
        at org.apache.ambari.server.api.services.BaseService.handleRequest(BaseService.java:164)
        at org.apache.ambari.server.api.services.BaseService.handleRequest(BaseService.java:128)
        at org.apache.ambari.server.api.services.HostComponentService.getHostComponents(HostComponentService.java:160)
        at sun.reflect.GeneratedMethodAccessor688.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.SubLocatorRule.accept(SubLocatorRule.java:137)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.apache.ambari.server.security.authorization.AmbariAuthorizationFilter.doFilter(AmbariAuthorizationFilter.java:299)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.apache.ambari.server.security.authentication.AmbariDelegatingAuthenticationFilter.doFilter(AmbariDelegatingAuthenticationFilter.java:135)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.apache.ambari.server.security.authorization.AmbariUserAuthorizationFilter.doFilter(AmbariUserAuthorizationFilter.java:95)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.apache.ambari.server.api.ContentTypeOverrideFilter.doFilter(ContentTypeOverrideFilter.java:146)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.apache.ambari.server.api.MethodOverrideFilter.doFilter(MethodOverrideFilter.java:73)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.apache.ambari.server.api.AmbariPersistFilter.doFilter(AmbariPersistFilter.java:53)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.apache.ambari.server.security.AbstractSecurityHeaderFilter.doFilter(AbstractSecurityHeaderFilter.java:135)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:51)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:740)
        at org.apache.ambari.server.controller.AmbariHandlerList.processHandlers(AmbariHandlerList.java:221)
        at org.apache.ambari.server.controller.AmbariHandlerList.processHandlers(AmbariHandlerList.java:210)
        at org.apache.ambari.server.controller.AmbariHandlerList.handle(AmbariHandlerList.java:140)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:503)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:750)
```

**Comment by Nazarii-Melnyk** [comment]
![image](https://github.com/user-attachments/assets/91e0b78c-8efd-48cc-91ff-8ba7e37a357a)

**Comment by Nazarii-Melnyk** [comment]
It looks like Ambari has a problem with work logic, because those metrics, like cpu_idle, read_bps (without separators) widget shows without any problems:

![image](https://github.com/user-attachments/assets/6046b09d-c371-467f-99fb-1041920814aa)

![image](https://github.com/user-attachments/assets/585ef397-80a9-444e-be92-7795d0d29843)

But metrics that have in theirs names separator `.` (like `jvm.JvmMetrics.*, yarn.*, rpc.*`) not available:

![image](https://github.com/user-attachments/assets/49dc410e-32b4-408c-994e-25862099f33e)

**Comment by Nazarii-Melnyk** [comment]
This bug was fixed on the Ambari side. 
Issue: https://github.com/rework-space-com/ambari/issues/20
PR: https://github.com/rework-space-com/ambari/pull/21
