### ISSUE TITLE
Add ranger into bigtop-3.2.1 from bigtop-3.3

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [rework-space-com/bigtop#35]
There are required to integrate Ranger service into the current Hadoop cluster deployment, that uses Bigtop-3.2.1 and Clemlab Ambari.

**Comment by Nazarii-Melnyk** [comment]
An error due Ranger service installation:
```
 Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/BGTP/1.0/services/RANGER/package/scripts/ranger_admin.py", line 262, in <module>
    RangerAdmin().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/BGTP/1.0/services/RANGER/package/scripts/ranger_admin.py", line 42, in install
    self.install_packages(env)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 843, in install_packages
    name = self.format_package_name(package['name'])
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 566, in format_package_name
    return self.get_package_from_available(name)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 533, in get_package_from_available
    raise Fail("No package found for {0}(expected name: {1})".format(name, name_with_version))
resource_management.core.exceptions.Fail: No package found for ranger-${stack_version}-admin(expected name: ranger-1-0-admin)
```

**Comment by Nazarii-Melnyk** [comment]
Error starting Ranger tagsync service:
```
Execute[(u'/usr/lib/jvm/java-8-openjdk-amd64/bin/java', '-cp', u'/usr/lib/bigtop-select/current/ranger-tagsync/lib/*', 'org.apache.ranger.credentialapi.buildks', 'create', 'tagadmin.user.password', '-value', [PROTECTED], '-provider', u'jceks://file/usr/bigtop/current/ranger-tagsync/conf/rangertagsync.jceks')] {'logoutput': True, 'environment': {'JAVA_HOME': u'/usr/lib/jvm/java-8-openjdk-amd64'}, 'sudo': True}
Error: Could not find or load main class org.apache.ranger.credentialapi.buildks
```

**Comment by Nazarii-Melnyk** [comment]
The Ranger service does not start using Bigtop-3.3 installation scripts. Error:
```
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/BGTP/1.0/services/RANGER/package/scripts/ranger_tagsync.py", line 146, in <module>
    RangerTagsync().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 355, in execute
    self.execute_prefix_function(self.command_name, 'post', env)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 386, in execute_prefix_function
    method(env)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 428, in post_start
    raise Fail("Pid file {0} doesn't exist after starting of the component.".format(pid_file))
resource_management.core.exceptions.Fail: Pid file /var/run/ranger/tagsync.pid doesn't exist after starting of the component.
```

**Comment by Nazarii-Melnyk** [comment]
Error while installing Ranger using Clemlab ODP installation scripts:
```
2024-10-10 14:00:55,252  [JISQL] /usr/lib/jvm/java-8-openjdk-amd64/bin/java  -cp /usr/lib/bigtop-select/current/ranger-admin/ews/lib/postgresql-42.7.3.jar:/usr/lib/bigtop-select/current/ranger-admin/jisql/lib/* org.apache.util.sql.Jisql -driver postgresql -cstring jdbc:postgresql://isv-s-hdp-mst-01.example.com/ranger -u rangeradmin -p '********' -noheader -trim -c \;  -query "delete from x_db_version_h where version = 'DEFAULT_ADMIN_UPDATE' and active = 'N' and updated_by='isv-s-hdp-mng-01.example.com';"
2024-10-10 14:00:55,738  [E] Ranger admin default password change request failed
```

Error in file `ranger_db_patch.log`:
```
ERROR o.a.r.p.c.ChangePasswordUtil (ChangePasswordUtil.java:106) Error loading
org.springframework.beans.factory.BeanInitializationException: Could not load properties; nested exception is java.io.FileNotFoundException: class path resource [core-site.xml] cannot be opened because it does not exist
```
